### ISSUE TITLE
Feature request : gpgs for multiplayer

### ISSUE THREAD

**Issue by ibenx** [xsellier/godotandroid#1]
Please add google play service realtime multiplayer, thanks for this useful module.. 😀

**Comment by xsellier** [comment]
I will add it, but right now I focusing on GDPR (due to 25th may 2018).

And if you need the realtime multiplayer or turn-by-turn ?
If you have an API to suggest, feel free to provide one ;)

**Comment by ibenx** [comment]
I use [this module](https://github.com/Kopfenheim/godot-gpgs) in my multiplayer game, all work fine (especially realtime multiplayer) but i need more functions on leaderboard like get current player score that i can get from your module..

**Comment by xsellier** [comment]
@ibenx Thank you, I will try to keep the same API.

**Comment by ibenx** [comment]
I am watching and i hope will use this module with realtime multiplayer included.. Keep it up tour good work.. 👍👍👍

**Comment by xsellier** [comment]
Google Play service is deprecating the multiplayer API.
Im closing this issue... Sorry

source:
https://www.xda-developers.com/google-ending-support-real-time-turn-based-multiplayer-api-play-games-services/
