### ISSUE TITLE
Suggestion: add Admob support on firebase

### ISSUE THREAD

**Issue by felipemattar** [xsellier/godotandroid#2]
Im trying use Google Play Services with Firebase/Admob, but after many tests combining several modules, no success.

like this one has Admob but no play services:
https://github.com/FrogSquare/GodotFireBase

**Comment by xsellier** [comment]
Hey, sorry but Im not going to support any ad feature. Feel free to fork the repo and to implement it.

**Comment by felipemattar** [comment]
Im trying with another module, but im using for reference. thanks

**Comment by xsellier** [comment]
@felipemattar I get you, however I dislike having ad in mobile games, so I won't support it in the module. Unless you implement it otherwise it won't be part of this module.
